spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: nj.zb.pojo                # 所有Pojo别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: dev
  application:
    name: provider-contact
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/exam201907?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false        # 数据库名称
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                 # 数据库连接池的最小维持连接数
      initial-size: 5             # 初始化连接数
      max-idle: 5                 # 最大连接数
      max-wait-millis: 200        # 等待连接获取最大超时时间
      test-while-idle: true
      validation-query: select 1
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: nj.zb.pojo                # 所有Pojo别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: test
  application:
    name: provider-contact
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/exam2019072?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false        # 数据库名称
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                 # 数据库连接池的最小维持连接数
      initial-size: 5             # 初始化连接数
      max-idle: 5                 # 最大连接数
      max-wait-millis: 200        # 等待连接获取最大超时时间
      test-while-idle: true
      validation-query: select 1
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
